stages:
  - test
  - build
  - deploy

services:
  - docker:dind

test:
  stage: test
  image: node:12
  only: master
  tags:
    - docker
  script:
    - yarn test:coverage
  artifacts:
    paths:
      - coverage/

build:
  stage: build
  image: node:12
  only: master
  tags:
    - docker
  before_script:
    - yarn install
  script:
    - yarn build
  artifacts:
    paths:
      - build/

deploy:
  stage: deploy
  image: slergberg/aws-deploy
  only: master
  tags:
    - docker
  script:
    - aws s3 rm --recursive "s3://${AWS_PRODUCTION_BUCKET}"
    - aws s3 sync ./build "s3://${AWS_PRODUCTION_BUCKET}"
  when: on_success
